import type { IR } from '@ironic/core';
import { fileHeader } from '../snippets/formatters.js';
import { snakeCase } from '../snippets/formatters.js';

export function emitPyprojectToml(ir: IR, moduleName: string): string {
  return `[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "${ir.meta.packageName}"
version = "${ir.meta.version}"
description = "${ir.meta.description}"
readme = "README.md"
requires-python = ">=3.9"
license = "Apache-2.0"
dependencies = [
    "httpx>=0.25.0",
    "typing_extensions>=4.7.0",
]

[project.urls]
Homepage = "${ir.meta.baseURL}"

[tool.hatch.build.targets.wheel]
packages = ["${moduleName}"]
`;
}

export function emitReadme(ir: IR, moduleName: string): string {
  const envVar = ir.auth.type !== 'none' ? ir.auth.envVar : 'API_KEY';

  return `# ${ir.meta.prettyName} Python SDK

${ir.meta.description}

## Installation

\`\`\`bash
pip install ${ir.meta.packageName}
\`\`\`

## Usage

\`\`\`python
from ${moduleName} import ${ir.meta.prettyName}

client = ${ir.meta.prettyName}(
    api_key="your-api-key",  # or set ${envVar} env var
)
\`\`\`

### Async usage

\`\`\`python
from ${moduleName} import Async${ir.meta.prettyName}

client = Async${ir.meta.prettyName}()
\`\`\`

---

*Generated by [Ironic](https://github.com/ironic-sdk/ironic).*
`;
}

export function emitPyTyped(): string {
  return '';
}

export function emitTopLevelInit(ir: IR): string {
  const lines: string[] = [
    fileHeader(),
    '',
    `from ._client import ${ir.meta.prettyName}, Async${ir.meta.prettyName}`,
    '',
    'from ._core import (',
    '    APIError,',
    '    APIConnectionError,',
    '    APITimeoutError,',
    '    BadRequestError,',
    '    AuthenticationError,',
    '    PermissionDeniedError,',
    '    NotFoundError,',
    '    ConflictError,',
    '    UnprocessableEntityError,',
    '    RateLimitError,',
    '    InternalServerError,',
    ')',
    '',
    'from .types import *  # noqa: F401,F403',
    '',
    `__all__ = [`,
    `    "${ir.meta.prettyName}",`,
    `    "Async${ir.meta.prettyName}",`,
    `    "APIError",`,
    `    "APIConnectionError",`,
    `    "APITimeoutError",`,
    `    "BadRequestError",`,
    `    "AuthenticationError",`,
    `    "PermissionDeniedError",`,
    `    "NotFoundError",`,
    `    "ConflictError",`,
    `    "UnprocessableEntityError",`,
    `    "RateLimitError",`,
    `    "InternalServerError",`,
    `]`,
    '',
  ];
  return lines.join('\n');
}

export function emitResourcesInit(ir: IR): string {
  const lines: string[] = [fileHeader(), ''];
  for (const resource of ir.resources) {
    const modName = snakeCase(resource.name);
    lines.push(
      `from .${modName} import ${resource.className}, Async${resource.className}`,
    );
  }
  lines.push('');
  return lines.join('\n');
}

export function emitTypesInit(typeFiles: string[]): string {
  const lines: string[] = [fileHeader(), ''];
  for (const file of typeFiles.sort()) {
    lines.push(`from .${file} import *  # noqa: F401,F403`);
  }
  lines.push('');
  return lines.join('\n');
}
