// ─── Package Scaffolding Emitters ────────────────────────────────────────────
// Emit package.json, tsconfig.json, index.ts for the generated SDK.

import type { IR } from '@ironic/core';

export function emitPackageJson(ir: IR): string {
  const pkg = {
    name: ir.meta.packageName,
    version: ir.meta.version,
    description: ir.meta.description,
    type: 'module',
    main: './dist/index.js',
    types: './dist/index.d.ts',
    exports: {
      '.': {
        import: './dist/index.js',
        types: './dist/index.d.ts',
      },
    },
    scripts: {
      build: 'tsc',
      prepublishOnly: 'npm run build',
    },
    engines: {
      node: '>=20',
    },
    files: ['dist', 'src'],
  };

  return JSON.stringify(pkg, null, 2) + '\n';
}

export function emitTsConfig(): string {
  const config = {
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'Bundler',
      strict: true,
      skipLibCheck: true,
      declaration: true,
      declarationMap: true,
      sourceMap: true,
      outDir: './dist',
      rootDir: './src',
      esModuleInterop: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      isolatedModules: true,
    },
    include: ['src'],
  };

  return JSON.stringify(config, null, 2) + '\n';
}

export function emitReadme(ir: IR): string {
  const envVarSection = ir.auth.type !== 'none'
    ? `\n## Authentication\n\nSet your API key:\n\n\`\`\`bash\nexport ${ir.auth.envVar}="your-api-key"\n\`\`\`\n\nOr pass it directly:\n\n\`\`\`typescript\nconst client = new ${ir.meta.prettyName}Client({ apiKey: 'your-api-key' });\n\`\`\`\n`
    : '';

  return `# ${ir.meta.packageName}

${ir.meta.description}

## Installation

\`\`\`bash
npm install ${ir.meta.packageName}
\`\`\`

## Usage

\`\`\`typescript
import { ${ir.meta.prettyName}Client } from '${ir.meta.packageName}';

const client = new ${ir.meta.prettyName}Client();
\`\`\`
${envVarSection}
---

*Generated by [Ironic](https://github.com/ironic-sdk/ironic).*
`;
}
